# Generated by Django 3.0.3 on 2020-03-08 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist_NArtist',
            fields=[
                ('artist', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('n_artist', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Userid_NUserId',
            fields=[
                ('userid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('n_userid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Userid_Profile',
            fields=[
                ('userid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('registered', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Userid_ProfileCalculado',
            fields=[
                ('userid_profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='taller1.Userid_Profile')),
                ('indiceJ', models.FloatField()),
                ('cosine', models.FloatField()),
                ('pearson', models.FloatField()),
            ],
            bases=('taller1.userid_profile',),
        ),
        migrations.CreateModel(
            name='Userid_Timestamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_timestamp', models.CharField(max_length=30)),
                ('codigo1', models.CharField(blank=True, max_length=50, null=True)),
                ('artist', models.CharField(max_length=300)),
                ('codigo2', models.CharField(blank=True, max_length=50, null=True)),
                ('song', models.CharField(max_length=400)),
                ('userid_Profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller1.Userid_Profile')),
            ],
            options={
                'ordering': ['-c_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Userid_Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_id', models.IntegerField()),
                ('count', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('userid_Profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller1.Userid_Profile')),
            ],
        ),
    ]
